# Generated by Django 5.0.4 on 2024-04-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
    ]
